POST /register
Host: localhost:8090
Content-Type: application/json

{
    "name": "김재진",
    "loginId": "kimjaejin",
    "password": "12345678",
    "email": "kimjaejin@gmail.com",
    "genderCode": "MALE",
    "birth": "2000-05-11",
    "nickname": "zzzzz"
}

###

POST /login
Host: localhost:8090
Content-Type: application/json

{
  "loginId" : "id1111111",
  "password" : "비밀번호입니다."
}

###