
POST /bridge/validate/post/4/user/1
Host: localhost:8090
Content-Type: application/json

{
	"user_validate" : [
                        {"user_id" : 1,
                          "template_name" : "이 집 잘하네"
                        },
                        {"user_id" : 2,
                          "template_name" : "밥경찰"
                        },
                        {"user_id" : 3,
                          "template_name" : "재미없어요"
                        }
    ]
}

###

#POST /bridge/validate/post/4/vote
#Host: localhost:8090
#Content-Type: application/json
#
#{
#		"validated_user_list" :[
#														{
#														 "user_name" : "kim",
#														 "script_title" : "이 집 잘하네"
#														},
#												    {
#														 "user_name" : "ads",
#														 "script_title" : "밥경찰"
#														}
#													]
#}
###


GET /bridge/validate/post/16/members
Host: localhost:8090
Content-Type: application/json



###



###